---
version: '3.9'
services:
  control:
    image: docker.io/mewitte1/redis-experiment:0.10
    networks:
      - 'redis'
    deploy:
      mode: replicated
      replicas: 1

  master:
    image: docker.io/mewitte1/redis-experiment:0.10
    hostname: "{{.Node.Hostname}}"
    environment:
      REDIS_MODE: 'master'
    networks:
      - 'redis'
    deploy:
      mode: replicated
      replicas: 1

networks:
  redis:
    external: true
    name: redis
