---
version: '3.9'
services:
  control:
    image: docker.io/mewitte1/redis-experiment:latest
    networks:
      - 'redis'
    deploy:
      mode: replicated
      replicas: 1

  master:
    image: docker.io/mewitte1/redis-experiment:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - 'redis'
    environment:
      REDIS_MODE: 'master'
      REPLICA_USER: 'replica-user'
      REPLICA_PASSWORD: 'replica-pass'
      SENTINEL_USER: 'sentinel-user'
      SENTINEL_PASSWORD: 'sentinel-pass'
    deploy:
      mode: replicated
      replicas: 1

  replica:
    image: docker.io/mewitte1/redis-experiment:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - 'redis'
    environment:
      REDIS_MODE: 'replica'
      REPLICA_USER: 'replica-user'
      REPLICA_PASSWORD: 'replica-pass'
      SENTINEL_IP: 'sentinel'
      SENTINEL_USER: 'sentinel-user'
      SENTINEL_PASSWORD: 'sentinel-pass'
    deploy:
      mode: replicated
      replicas: 3

  sentinel:
    image: docker.io/mewitte1/redis-experiment-sentinel:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - 'redis'
    environment:
      REDIS_MASTER_IP: 'master'
      REDIS_USER: 'redis-user'
      REDIS_PASSWORD: 'redis-pass'
      SENTINEL_IP: 'sentinel'
      SENTINEL_USER: 'sentinel-user'
      SENTINEL_PASSWORD: 'sentinel-pass'
      SENTINEL_ADMIN_USER: 'admin'
      SENTINEL_ADMIN_PASSWORD: 'admin'
    deploy:
      mode: replicated
      replicas: 3

networks:
  redis:
    external: true
    name: redis
